# Top 10 Revenue generated products

query = '''
SELECT
    p.product_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.total_price) AS total_revenue,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(AVG(oi.total_price), 2) AS avg_item_revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 10;
'''

total_revenue = pd.read_sql(query, engine)
print(total_revenue)



# Revenue generated by categories

query = '''
SELECT
    c.category_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.total_price) AS total_revenue,
    ROUND(AVG(oi.total_price), 2) AS avg_item_revenue
FROM categories c
JOIN products p ON c.category_id = p.category_id
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o ON oi.order_id = o.order_id
GROUP BY c.category_name
ORDER BY total_revenue DESC;
'''

top_categories = pd.read_sql(query, engine)
print(top_categories)



# revenue by brand

query = '''
SELECT
    p.brand,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.total_price) AS total_revenue,
    ROUND(AVG(oi.total_price),2) AS avg_order_value
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
GROUP BY p.brand;
'''

revenue_by_brand = pd.read_sql(query, engine)
print(revenue_by_brand)



# Top 10 products by quantity sold

query = '''
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 10;
'''

top_sold_products = pd.read_sql(query,engine)
print(top_sold_products)




# Number of customers per segment

query = '''
SELECT
    customer_segment,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_segment
ORDER BY customer_segment
'''

customers_per_segment = pd.read_sql(query, engine)
print(customers_per_segment)